@startuml
scale max 3000*3000
hide empty members
hide empty methods

skinparam titleFontSize 30
skinparam titleFontColor Plum
title
UML diagram: TodoList
endtitle

legend
get/sets & interface implementations ommited for clarity
endlegend

class Task {
    - {static} currentID: int
    - id: int
    - description: String
    - importance: Importance
    - creationDate: LocalDate
    - dueDate: LocalDate
    - categories: Set<String>
    - users: Set<String>
    - completed: boolean
}

enum Importance {
    HIGH
    MEDIUM
    LOW
}

class TaskManager {
    - tasks: Set<Task>
    ==
    + addTask(task: Task): void
    + removeTask(task: Task): boolean
    + getTasks(): Collection<Task>
}

class Main {
    + {static} main(args: String[]): void
}

class ArgParser {
    + {static} parse(args: String[]): Command
}

class Configuration {
    - {static} configFile: File
    + {static} save(): void
    + {static} load(): void
}

interface TaskSorter {
    + sort(tasks: Collection<Task>): Collection<Task>
}

interface TaskFilter {
    + filter(tasks: Collection<Task>): void
}

interface Command {
    + execute(...): void
}

interface ChangeListener {
    + onChange(): void
}

class Server {
    - listeners: List<ChangeListener>
    ==
    + registerListener(listener: ChangeListener): void
    + unregisterListener(listener: ChangeListener): void
    ..
    + executeCommand(command: Command): void
}

class CliClient
class GuiClient 

Main ..> Server

!define cl(x) x ..|> ChangeListener
cl(CliClient)
cl(GuiClient)
cl(Configuration)

ChangeListener --* Server

Server <-- GuiClient
Server <-- CliClient

TaskManager <.. Command

' ..|> Implementation
' --|> Héritage

' --o Agrégation
' --* Composition
' --> Association
' ..> Dépendence

TaskSorter <.. Command
TaskFilter <.. Command

Task o-- Importance

Main --* Command
Main --* ArgParser

Task --o TaskManager 

@enduml
